###
# Configuration for Vagrant
###
name: wceu2017-demo
production:
  # This is used to automatically fetch data from a staging/production environment
  domain: wceu2017-demo.seravo.com
  ssh_port: 10045
  url: https://wceu2017-demo.seravo.com
development:
  # Domains are automatically mapped to Vagrant with /etc/hosts modifications
  domains:
    - wceu2017-demo.local
  # If you want to use zeroconf (.local domains) in your network you can use this.
  #avahi: true
